[package]
name = "eerie"
version = "0.2.6"
edition = "2021"
license = "Apache-2.0"
authors = ["Gyungmin Myung"]
description = "Rustic binding to the IREE Compiler/Runtime"
readme = "README.md"
repository = "https://github.com/gmmyung/eerie"

[dependencies]
eerie-sys = { path = "eerie-sys", version = "0.2.6", default-features = false }
thiserror = { version = "1.0.48", optional = true }
defmt-or-log = { version = "0.2.3", default-features = false }
half = { version = "2.6.0", default-features = false }
defmt = { version = "1.0.0", optional = true }
log = { version = "0.4.26", optional = true }

[workspace]
members = [
    "eerie-sys"
]

[dev-dependencies]
anyhow = "1.0.75"
test-log = { version = "0.2.12" }
env_logger = "0.11.1"

[features]
default = ["runtime", "compiler", "std"]
runtime = ["eerie-sys/runtime", "defmt"]
compiler = ["eerie-sys/compiler", "std"]
std = ["dep:thiserror", "eerie-sys/std"]
cuda = ["eerie-sys/cuda"]
defmt = ["defmt-or-log/defmt", "dep:defmt"]
log = ["defmt-or-log/log", "dep:log"]

[[example]]
name = "resnet"
test = false
bench = true
